/*CRIANDO A SEQUENCIA*/
CREATE SEQUENCE CODIGOO
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;

/*CRIANDO TABELA*/
CREATE TABLE ESTOQUE 
(COD_PROD NUMBER(3), 
DESCR_PROD VARCHAR(15) CONSTRAINT DESCR_PROD_NN NOT NULL, 
DEPTO_PROD VARCHAR(15),
QUANT_PROD NUMBER (4,0), 
VALOR_PROD NUMBER(6,2)CONSTRAINT VALOR_PROD_NN NOT NULL);

DESC ESTOQUE;
SELECT * FROM ESTOQUE;

/*INSERINDO OS DADOS*/
INSERT INTO ESTOQUE (COD_PROD, DESCR_PROD, DEPTO_PROD, QUANT_PROD, VALOR_PROD) 
VALUES (CODIGOO.NEXTVAL,'GRAMPO','ESCRITORIO',5,'10,57'); 

INSERT INTO ESTOQUE (COD_PROD, DESCR_PROD, DEPTO_PROD, QUANT_PROD, VALOR_PROD) 
VALUES (CODIGOO.NEXTVAL,'PREGOS 10"x2"','PRODUÇÃO',20,'6,78'); 

INSERT INTO ESTOQUE (COD_PROD, DESCR_PROD, DEPTO_PROD, QUANT_PROD, VALOR_PROD) 
VALUES (CODIGOO.NEXTVAL,'CALCULADORAS','CONTABILIDADE',6,'52,37'); 

/*ALTERAÇÕES NA TABELA*/

/*ADICIONAR CHAVE PRIMARIA EM COD_PROD*/
ALTER TABLE ESTOQUE ADD CONSTRAINT COD_PROD_PK PRIMARY KEY (COD_PROD);

/*TRANSFORMAR DEPTO_PROD EM NAO NULO*/
ALTER TABLE ESTOQUE MODIFY (DEPTO_PROD CONSTRAINT DEPTO_PROD_NN NOT NULL);

/*INSIRA A COLUNA UNID_PROD NOT NULL*/

ALTER TABLE ESTOQUE ADD UNID_PROD VARCHAR2(15) DEFAULT 'A';
ALTER TABLE ESTOQUE MODIFY UNID_PROD CONSTRAINT UNID_PROD_NN NOT NULL;

/*ATUALIZANDO AS LINHAS*/
UPDATE ESTOQUE SET UNID_PROD = 'Cx.c/500' WHERE COD_PROD =  1;
UPDATE ESTOQUE SET UNID_PROD = 'Milhar' WHERE COD_PROD =  2;
UPDATE ESTOQUE SET UNID_PROD = 'Unidade' WHERE COD_PROD =  3;

/*ELIMINAR A REGRA NOT NULL*/
ALTER TABLE ESTOQUE DROP CONSTRAINT UNID_PROD_NN;
