CREATE TABLE FUNCIONARIOO (MATRICULA INT PRIMARY KEY, NOME VARCHAR2(12), DATA_ADMIS DATE);
SELECT * FROM FUNCIONARIOO;

/*ADICIONANDO OS VALORES*/
INSERT INTO FUNCIONARIOO VALUES (1, 'CLAUDIA','10-10-2018');
INSERT INTO FUNCIONARIOO VALUES (2, 'SILVIO','12-07-2000');
INSERT INTO FUNCIONARIOO VALUES (3, 'VANESSA','10-08-2010');
INSERT INTO FUNCIONARIOO VALUES (4, 'RICARDO','04-08-2000');

/*ORDER BY, AQUI FOI DECLARADO O NOME E DATA EM ORDEM CRESCENTE (ASC)*/
SELECT NOME, DATA_ADMIS FROM FUNCIONARIOO ORDER BY NOME ASC;

/*PARA SELECIONAR APENAS A MATRICULA 1*/
SELECT MATRICULA, NOME FROM FUNCIONARIOO WHERE MATRICULA = 1;

/*PARA SELECIONAR AS DATAS DE ADMISSAO DIFERENTES DE 12-07-2000*/
SELECT * FROM FUNCIONARIOO WHERE DATA_ADMIS <> '12-07-2000';

/*PARA SELECIONAR AS MATRICULAS QUE SEJAM MAIOR QUE 2*/
SELECT * FROM FUNCIONARIOO WHERE MATRICULA > 2;

/*PARA SELECIONAR O NOME E DATA DE ADMISSAO QUE SEJA MAIOR OU IGUAL A 10-08-2000*/
SELECT NOME, DATA_ADMIS FROM FUNCIONARIOO WHERE DATA_ADMIS >='10-08-2000';

/*PARA SELECIONAR A MATRICULA E NOME QUE POSSUEM A DATA MENOR QUE 10-08-2010*/
SELECT MATRICULA, NOME FROM FUNCIONARIOO WHERE DATA_ADMIS < '10-08-2010';

/*PARA SELECIONAR/PROCURAR A PALAVRA "CAR" ENTRE OS TEXTOS DE TODA TABELA*/
SELECT MATRICULA, NOME FROM FUNCIONARIOO WHERE NOME LIKE '%CAR%';

/*ADICIONANDO MAIS INFORMAÇÕES NA TABELA, POREM COM VALORES NULOS NAS DATAS*/
INSERT INTO FUNCIONARIOO (MATRICULA, NOME) VALUES (5,'LIA');
INSERT INTO FUNCIONARIOO (MATRICULA, NOME) VALUES (6,'RUY');

/*AGORA QUE FORAM ADICIONADOS, SELECIONE OS VALORES NULOS*/
SELECT * FROM FUNCIONARIOO WHERE DATA_ADMIS IS NULL;

/*E PARA VER OS VALORES QUE NÃO SAO NULOS*/
SELECT * FROM FUNCIONARIOO WHERE DATA_ADMIS IS NOT NULL;

/*SELECIONE AS LINHAS EM QUE TODOS OS VALORES SÃO VERDADEIROS*/
SELECT * FROM FUNCIONARIOO WHERE MATRICULA > 2 AND DATA_ADMIS > '31-12-2000';

/*SELECIONE AS LINHAS EM QUE PELO MENOS UM VALOR SEJA VERDADEIRO*/
SELECT * FROM FUNCIONARIOO WHERE MATRICULA >=3 OR DATA_ADMIS > '31-12-2010';
/*SELECIONE AS LINHAS EM QUE OS VALORES SEJAM VERDADEIROS OU FALSOS E NAO NULOS*/
SELECT * FROM FUNCIONARIOO WHERE (MATRICULA >=3 OR DATA_ADMIS >'31-12-2010') 
AND DATA_ADMIS IS NOT NULL;

/*SELECIONE AS LINHAS QUE ESTAO EM UM INTEVALO DE VALORES DETERMINADO*/
SELECT MATRICULA, NOME FROM FUNCIONARIOO WHERE MATRICULA BETWEEN 2 AND 3;


