/*CRIANDO OBJETO SEQUENCIA*/

/*CRIA UM GERADOR DE NUMEROS SEQUENCIAIS*/
CREATE SEQUENCE MAIS_UM
/*VALOR MINIMO QUE A SEQUENCIA PODE GERAR*/
MINVALUE 1
/*PERMITE INICIAR COM QUALQUER VALOR, AQUI COMEÇOU COM 1*/
START WITH 1
/*ESPECIFICA O VALOR A SER ADICIONADO AO VALOR CORRENTE DA SEQUENCIA P/ GERAR O NOVO VALOR*/
INCREMENT BY 1
/*ESPECIFICA QUANTOS NUMETOS DEVER SER PRÉ-ALOCADOS E ARMAZENADOS EM MEMORIA P/ ACESSO MAIS RAPIDO*/
CACHE 10;

CREATE TABLE VENDEDOR (COD_VENDEDOR NUMBER(3), NOME_VEND VARCHAR(15)CONSTRAINT NOME_VEND_NN NOT NULL, 
SEXO CHAR(1) CONSTRAINT SEXO_VEND_CK CHECK (SEXO IN ('M','F')));
/*DESCREVER OS DADOS IMPOSTOS NA TABELA*/
DESC VENDEDOR;

SELECT * FROM VENDEDOR;

INSERT INTO VENDEDOR (COD_VENDEDOR, NOME_VEND, SEXO) VALUES (MAIS_UM.NEXTVAL, 'LIA','F');
INSERT INTO VENDEDOR (COD_VENDEDOR, NOME_VEND, SEXO) VALUES (MAIS_UM.NEXTVAL, 'JOSÉ','M');
INSERT INTO VENDEDOR (COD_VENDEDOR, NOME_VEND, SEXO) VALUES (MAIS_UM.NEXTVAL, 'RUY','X');

/*CRIANDO UMA NOVA COLUNA*/
ALTER TABLE VENDEDOR ADD (DATA_REG DATE);

INSERT INTO VENDEDOR (COD_VENDEDOR, NOME_VEND, SEXO, DATA_REG) VALUES (MAIS_UM.NEXTVAL, 'ANA','F','28-10-2020');

/*FAZENDO OPERAÇÕES COM DATA*/
/*SOMAR 10 DIAS A DATA DE REGISTRO DA ANA*/
/*O COD DA ANA É 4 POIS O RUY FOI 3 MAS OS DADOS SÃO INVALIDOS*/
UPDATE VENDEDOR SET DATA_REG = DATA_REG + 10 WHERE COD_VENDEDOR = 4;

/*ELMINAR A COLUNA SEXO*/
ALTER TABLE VENDEDOR DROP COLUMN SEXO;

/*ATUALIZANDO VARIAS DATAS*/
UPDATE VENDEDOR SET DATA_REG = '3-2-17' WHERE COD_VENDEDOR < 3;

/*ELIMINANDO RESTRIÇÕES*/
ALTER TABLE VENDEDOR DROP CONSTRAINT SEXO_VEND_CK;

INSERT INTO VENDEDOR (COD_VENDEDOR, NOME_VEND, SEXO,DATA_REG) 
VALUES (MAIS_UM.NEXTVAL, 'LUIS','X','01-06-2015');

/*AUMENTANDO O TAMANHO DO CAMPO SEXO*/
ALTER TABLE VENDEDOR MODIFY (SEXO VARCHAR (10));

UPDATE VENDEDOR SET SEXO = 'FEMINO' WHERE SEXO = 'F';
UPDATE VENDEDOR SET SEXO = 'MASCULINO' WHERE SEXO = 'M';

/*ADICIONANDO UMA CHAVE PRIMARIA*/
ALTER TABLE VENDEDOR ADD CONSTRAINT COD_VENDEDOR_PK PRIMARY KEY (COD_VENDEDOR);

/*AUMENTAR O TAMANHO DO NOME_VEND DE 15 P/ 20*/
ALTER TABLE VENDEDOR MODIFY (NOME_VEND VARCHAR(20));

/*RENOMEAR O CAMPO NOME_VEND PARA VENDEDORES*/
ALTER TABLE VENDEDOR RENAME COLUMN NOME_VEND TO VENDEDORES;



